apiVersion: v1
kind: Secret
metadata:
  name: superset-secrets
type: Opaque
stringData:
  ADMIN_USERNAME: admin
  POSTGRES_PASSWORD: "REPLACE_ME_POSTGRES_PASSWORD"
  SUPERSET_SECRET_KEY: "REPLACE_ME_SUPERSET_SECRET_KEY"
  ADMIN_PASSWORD: Superset@123

