apiVersion: v1
kind: Secret
metadata:
  name: superset-secrets
type: Opaque
stringData:
  POSTGRES_PASSWORD: "REPLACE_ME_POSTGRES_PASSWORD"
  SUPERSET_SECRET_KEY: "REPLACE_ME_SUPERSET_SECRET_KEY"
  ADMIN_PASSWORD: "REPLACE_ME_ADMIN_PASSWORD"
